realm: "xphoenix.org"

log:
  format: text
  out: console
  level: debug

http:
#  iface: 127.0.0.1
  port: 8080

https:
#  iface: 127.0.0.1
  port: 8443
  key: xphoenix.org.key
  crt: xphoenix.org.cert

providers:
  - directory:///home/andrphi/.zones
  - mongodb://localhost:27017/cerber
